### ISSUE TITLE
Document why we skip on more than one valid header?

### ISSUE THREAD

**Issue by azul** [autocrypt/autocrypt#102]
(from a todo in The Autocrypt Header on line 390 of level1.rst)

**Comment by dkg** [comment]
The goal is simplicity, and it's not clear that there is a motivation for a client to want to send multiple keys of the same type for themselves.

So, we skip on more than one valid header per `<peer,type>` because:

 * conformant peers will send only a single header, so this looks like something is wrong.
 * if we see more than one header, then we have to make a decision about what to do with the extra headers.  store them all?  store the first one?  store the last one?
 * if we choose to store all the headers found per `<peer,type>` tuple, then replacement/combination/counting becomes significantly more complicated from the state management perspective.  What happens when you get message A with headers X,Y and prefer-encrypt=mutual and then message B with headers X,Z and no prefer-encrypt ?
 * if multiple headers are stored per `<peer,type>` tuple, then making an autocrypt recommendation is also more complicated.  Do we recommend multiple keys for encryption?
 * in the future, if there is some sort of "autocrypt address" or "autocrypt number" for peer key confirmation, how will it look if there are multiple keys for a given `<peer,type>` tuple?

What is the use case where a peer might want to send multiple keys of the same type for themselves?

**Comment by dkg** [comment]
I think this is now resolved, since the merge of #123
