### ISSUE TITLE
Specify interaction with Spam filtering

### ISSUE THREAD

**Issue by azul** [autocrypt/autocrypt#103]
(copied from a todo in Updating Autocrypt Peer State):

```
528 .. todo::
529 
530    the spec currently doesn't say how to integrate Autocrypt
531    processing on message receipt with spam filtering.  Should we say
532    something about not doing Autocrypt processing on message receipt
533    if the message is believed to be spam?

```

**Comment by r10s** [comment]
Maybe it is no good idea to parse the Autocrypt header if the message is believed to be spam, I have no strong opinion on that.
However, I can easily imagine that this may get complicated for implementors, eg. as Autocrypt parsing may be done delayed when the message is manually marked as "no spam". And: What for the other way: An already parsed Autocrypt-header is marked as spam. I think, currently, we cannot "rollback" the peerstate.

**Comment by hpk42** [comment]
@r10s is it a big deal to say that "MUAs MUST NOT parse Autocrypt headers which are contained in mails that are flagged as 'spam'"? The flagging can happen through avoiding mails in certain folders (or positively, only considering mails from known to be "good" folders").  If i remember correctly then @Valodim rather parses headers only when a message is actually displayed which mostly circumvents the problem and is IMO a valid solution.

**Comment by dkg** [comment]
i think MUST NOT is a little bit harsh, specifically because of @r10s ' point that we don't have a way to "roll back" header ingestion.  "flagged as spam" is something that can change over time for a given message.  if something starts off flagged as spam, and then we un-flag it, that's easy.  but going the other way is hard/impossible.

Even if you delay header ingestion until display time, it's possible that a message only gets marked as spam (by the user) after display, at which point the header has already been ingested.
