### ISSUE TITLE
Use of IMAP METADATA

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#12]
There is an imap extension called `IMAP METADATA`, specified in [rfc 5464](https://www.ietf.org/rfc/rfc5464.txt). This extension basically provides a key-value store per mailbox (so more of a box-key-value store?), allowing storage of arbitrary data associated to any mailbox in addition to an arbitrary key.

So the good news is, using this would make our lives doing inter-MUA communication a lot easier, since the mechanism is actually meant to be used in the way we want. The bad news is, this extension is [not exactly widely supported](http://www.imapwiki.org/Specs), so even if we take a bet on its wider adoption in the future we will need a feedback.

I'm not sure this is worth the effort, just leaving this issue here as a note to think about later on.

**Comment by dkg** [comment]
This is an interesting option, but i'm already wary that level 0 seems to be IMAP-dependent.  Some popular MUAs (e.g. outlook) don't even use IMAP for their typical connnections (they use MAPI to their configured exchange server), and we haven't specified what the "namespaced access" looks like to them.

As much as i like the IMAP METADATA suggestion, i think we have the simplest possible story for level 0 without it: level 0 clients need to be IMAP clients able to navigate and create folders.

if we want to think about how to take advantage of this for level 1 or later, i suppose that's possible, but i'm hoping that level 1 would be *more* generic than imap (e.g. supporting arbitrary "namespaced folders" regardless of protocol) rather than a subset of imap servers (which would be the result of relying on IMAP METADATA).

**Comment by Valodim** [comment]
I agree, although I think that later transitioning will be close to impossible once the non-capable clients are out there.

The hypothetical battle plan would be to abstract the inter-MUA communication, require support for rfc5464 METADATA, and fall back to mailbox storage if that isn't available. If we do anything else, clients can never know if some other autocrypt client wants access but doesn't support METADATA, which means they will always have to do that anyways.

The complexity to have this now is relatively small, both on an absolute scale, and when compared to introducing it later on. However, there is close to zero immediate gain, we don't know if the imap mailbox drawbacks are even an actual problem for users, *and* using IMAP METADATA really nails us down to imap.

I currently tend to the opinion that it's not worth it. I just want to be sure we make a conscious and documented decision here :)
