### ISSUE TITLE
Gossip key can override more recent "direct" key, potentially causing more unreadable mails

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#248]
Suppose the follow scenario:

- T-42 days: ``Carol`` sends Alice a mail with an Autocrypt header, Alice responds.  

- T-41 days: Carol loses her device and reinstalls her mail app, resulting in a new Autocrypt key for future mails

- T-40 days: Carol writes bob a mail "damn i lost my device, " and otherwise they chat to tentatively agree for a joint date with Alice at time T. 

- T-30 days: Bob writes Alice a mail about jointly meeting at time T, she responds and says she will fix the time and location and send a mail around. 

- T-1: Alice writes Bob and Carol a mail about meeting location and precise T time for the three of them. Bob can read Alice's mail and group-replies with an attachment he wants to discuss and asks for feedback.  With the current logic, Bob will now use Carol's  stale key because Alice just gossiped it and his own state for Carol's key is from T-40 days, i.e. older than 35 days.   Alice and Bob exchange group-replies in preparation for the meeting.  Bob didn't hear back anything from Carol so also sends her a direct message. 

- T: Carol opens her mail client and can not read Alice's or bob's group mails and can not read Bob's direct mail either. She has no idea what is going on.  Didn't she successfully chat with Bob at T-40 days? She  group-mails back but answering takes a while because Alice/Bob are travelling ...  They eventually manage to meet and jointly decide to disable Autocrypt because it's causing too much trouble. 

There are variants on this.  Effectively i think that it's usability-wise dangerous to prefer a gossip key over a directly received one by taking the message date when a key was gossiped as significant. In the above situation, if Bob would have used his T-40 key from Carol, Carol would be able to read his group-reply to Alice's invitation at least and also the direct message from Bob. And if Alice would take the Carol-key from Bob during their T-1 conversation, Carol would only ever have seen one unreadable mail (the original one from Alice) instead of many. 

The preliminary recommendation 35 day logic was only introduced very recently (#209). We have no implementations for it so i think we should be careful in considering this.

**Comment by nwalfield** [comment]
One way to fix this is to include the autocrypt_timestamp when gossiping a key.  I suggested this and dkg pointed out that it is a serious privacy leak.  An alternative, is to use round(log(now - autocrypt_timestamp)).  This is a compromise that can significantly reduce the amount of information leaked as a function of the log's base.  But, even this exposes a fair amount of personal data (oh, you exchanged emails with X recently!)

**Comment by Valodim** [comment]
Phew, took me a while to get through the example with all the fluff.

We can abstract over this a little, since the scenario effectively comes down to a tradeoff between two positions:

1) We take gossip keys over a direct one if the direct one is stale after a while
2) We prefer our own key over the gossiped one

Arbitrary in-betweens are possible based on the timestamps of our own key, or the introduction of a gossip-timestamp. Anyways, in a situation where we actually have to chose, one of the keys *will* be the wrong one. So let's look at the two failure modes:

For 1), we will encrypt to the public key that was also used in the original message. In my eyes, this is a consistent way of failing, since the mail will be just as unreadable as the one being replied to.

For 2), the original message will be readable, but our reply will not. Or otherwise, the original message will be readable but our message will be unreadable.

In both cases the situation can be fixed by the person in question replying. Any way I look at it, the scenario with inconsistent readability (2) within the same thread feels strictly worse than the consistent one (1).

**Comment by dkg** [comment]
@nwalfield IIUC, your suggestion is the same as #243 .  And yeah, i think it's problematic.

Here's a way around it:

 * Only ever use gossipped keys in a reply situation, where you need to encrypt, but you don't have a directly-received key for the peer.

That solves the reply-to-encrypted-mail case, and presents a simple rule.   It also means that if you tried to encrypt a non-reply mail to that person without having a directly-received key for them, the Autocrypt recommendation would be "disable" (see #212 for related ideas).

**Comment by dkg** [comment]
@Valodim - -  one advantage of your "inconsistent readability" state (2) over "consistent unreadability" (1) is that if Carol can at least read one message in the thread, she can learn the other recipient's keys from the sender of the readable mail.  Otherwise, her "i can't read this" reply to the list is necessarily in the clear.

*shrug* -- i think this is a corner case, and i'm not convinced there is a full solution around it that doesn't open up some other scenario where we would all agree that there's a possible bad state.

So we just need to be clear that such states exist, and make sure we've thought through how a user might respond to them effectively.

**Comment by hpk42** [comment]
@valodim i think in a situation where Alice and bob use different keys for encryption to Carol within a Alice/Bob/Carol group communication, that for Carol to be able to read half the messages is actually better than Carol not being able to read anything (which happens because alice gossips a stale key and bob think's it's better than his own actually fresher key through the 35day logic).  

I tentatively think that gossip keys should in L1 never override directly received ones. Anything more involved can be done post-L1.  This would mean striking the 35 day logic and getting rid of ``gossip_timestamp`` -- this is the state of the spec >6 days ago IISIC.
