### ISSUE TITLE
Autocrypt Setup Message: application/autocrypt-setup Content-Disposition

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#264]
We don't say the Content-Disposition allowed in https://github.com/autocrypt/autocrypt/blob/master/doc/level1.rst#L836, can be both inline or attachment?. 
In the appendix example https://github.com/autocrypt/autocrypt/blob/master/doc/appendix/example-setup-message.eml, initially generated by Enigmail, it's attachment.
We also don't say whether html is allowed in the text above or below the ASCII-armored encrypted data, though probably this is less relevant, as that part is ignored while processing. We have html in the example.

**Comment by dkg** [comment]
Let's call the two top-level subparts of the autocrypt setup message the "surface" (the first part, human-readable) and the "payload" (the second part,  `Content-Type: application/autocrypt-setup`)

so there are two questions asked here, both about the payload:

 * Can we put html in the plaintext of the payload (above or below the ASCII-armored OpenPGP blob)?
 * Do we care what the `Content-Disposition` of the payload is (`attachment` vs `inline`)?

I think neither question matters for the "standard" workflow, where we expect both MUAs to access the message directly from the message store they both have access to.

But these questions pertain to a non-standard workflow not explicitly spelled out in the existing draft.  I think the non-standard workflow that we'd like to make possible is something like:

 * user saves (some part of?) the setup message somewhere, outside of the MUA (presumably, in a file, in the traditional desktop-computing model)
 * user imports that saved thing manually into some other MUA

And, out of concern for user-friendliness:
 
 * if the user encounters the saved thing on their own, and they want to see what it is, they should get to see something that they can understand.

--------
Based on those assumptions, i think the expectation is that the user would save the payload itself (not the full message) as a file.  So that implies:

 * We should encourage the MUA to present the payload as a "thing to be saved", which means encouraging `Content-Disposition: attachment`
 * It is OK to put html in the payload, but we probably only want to do that if the `filename=` MIME attribute ends in `.html` -- is because the MUA will propose saving the file as `whatever.html`.  then, once it's in the filesystem, "clicking on it" will result in opening it with a browser, which would then be able to render the human-readable part to the user.

That's my take on it, anyway.

**Comment by juga0** [comment]
In that case, should we add to the "payload" spec something like?: 

    The ``Content-Disposition`` SHOULD be ``attachment`` to facilitate the user to download the      payload as a separate file" [...] The human readable text can be plain text or html

**Comment by dkg** [comment]
I've got no objection to that as long as it doesn't add a ton of text.  guidance to do the sensible thing sounds reasonable.  I'd say make a PR with the changes that you think would help new implementers.
