### ISSUE TITLE
how to transfer multiple secret keys in setup message? 

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#267]
Brought up by a review from Benny from the L1.0.0rc1-Nov22 built: what is the current idea on how to transfer multiple secret keys in the setup message?  

use case: If a MUA regenerates a secret key (i.e. sends out a new key) it still wants to retain the former secret key in order to be able to decrypt messages encrypted to it.  This is neccessary as there is no way to push out key updates to peers other than regular e-mail messages.  If such a MUA with two secret keys wants to transfer both secret keys to another autocrypt-capable MUA, how would it construct the message?

Could it add a third ``application/autocrypt-setup`` mime part to the ``multipart/mixed`` [message structure](https://autocrypt.org/en/latest/level1.html#message-structure)?  and could this be specified in a 1.1 backward-compatible release of the spec?  

it seems that the current wording forbids having multiple secret keys in the ``application/autocrypt-setup`` part as it "MUST" ignore anything before and after the single secret key. 

i think this issue needs to be clarified before 1.0 final (not neccessarily resulting in a spec change, but maybe into e.g. a FAQ entry).

**Comment by freron** [comment]
A few extra thoughts on the subject:

It seems to me that it would be fine to allow the `multipart/mixed` part to have multiple `application/autocrypt-setup` subparts. The first one should be the one used for new messages -- as it is now. Maybe specify that the first one MUST be processed and the others SHOULD be processed.

Also, the passphrase must be the same for all of the keys in order to avoid entering multiple setup codes. An expert (not me) should check if this somehow weakens the security.

Given the above then it could also be emphasized that the MUA should only process the most recent “Autocrypt Setup Message” found for a given identity (if the MUA supports automatically looking for these).

**Comment by dkg** [comment]
Just a note of clarification -- the current setup message is *intended* to transport two secret key mathematical objects in the `application/autocrypt-setup` part -- the secret key for the primary key, and the secret key for the subkey.  I know that this is all part of a single "OpenPGP Transferable Secret Key", and i think that this issue is asking about multiple "transferable secret keys" instead, though.

The current spec does not contemplate retention of any previously-held secret keys for an account.  I agree that this is something a sensible MUA might want to do, but we don't spec it out at all at the moment (e.g. there is no `accounts[A].historical_secret_keys` field), which makes it tough to specify how a user agent might handle multiple keys in a setup message.

That said, i think @freron is on the right track here.  We should specify that the first `application/autocrypt-setup` part MUST be processed, and allow that there may be multiple following `application/autocrypt-setup` parts.

I do *not* think that we should say that the subsequent parts SHOULD be processed without explicitly saying how to process them, which would require adding an `accounts[A].historical_secret_keys` field or something.

I agree with @freron that the same passphrase must be used for all subsequent parts.  As long as the encrypted messages use an SKESK that actually embeds a randomized session key (and the session keys differ across each part) i don't think that there is any additional security problem introduced by sharing the passphrase, but i'd need to do more analysis and probably ask more people to be certain.

@freron writes:
>Given the above then it could also be emphasized that the MUA should only process the most recent “Autocrypt Setup Message” found for a given identity (if the MUA supports automatically looking for these).

I'm not sure how this follows.  This seems like an orthogonal discussion to me, and i don't think we should mix it in here.

**Comment by hpk42** [comment]
Why can we not just allow multiple openpgp transferable secret keys in the application/autocrypt-setup message and say that if a MUA wants to also transfer "historic" ones, it can put them after the first one?  This seems nice and simple and does not require much further analysis.

**Comment by dkg** [comment]
It's easy to say what can go here.  it's harder to say what a MUA should do if it finds multiple keys here.

at the moment, we basically say "store the key we found here in `accounts[A]`" -- but `accounts[A]` doesn't mention what to do with multiple OpenPGP certificates, so we've created a problem for MUAs without advising them on how to solve it.

**Comment by Valodim** [comment]
We should probably at some point introduce a notion of historical keys into the spec. I wonder if that point is now, though :hurtrealbad: 

One very interesting property of historical keys is that they can be used as an interoperable solution to the scenario where multiple MUAs generate conflicting autocrypt keys by accident. Since keys have a creation time (caveat: openpgp-specific), we can easily spec that all but the latest key should be used for historical purposes only. This can also be enforced on the sender side by only including encryption subkeys in such keys. Got mail that is only readable by another client? Send a setup message from that client, and you're done. That would also make sure that we do the right thing if an old autocrypt setup message is imported.

We *can* put more than one key in a single autocrypt-setup part. The advantage is that it's easier and cleaner to implement, compared to reusing passphrases between multiple MIME attachments. The disadvantage is that this is rather openpgp-specific (`-----BEGIN` awareness), but we actually have that already.

I think we can improve the spec a lot if we can get this right. But doing too much in v1 would drag the spec quite a bit in the wrong direction on the battle tested vs speculative design by committee spectrum. This applies more to changes in behavior, than changes in format. I would introduce minimum required details to make sure we are forward compatible, and proceed with a more fleshed out mechanism in v1.1 (or v2.0).

I'd like to brainstorm reducing the openpgp-specificity of the autocrypt-setup-message a bit. Looking at that again with some distance I don't really like the way we handle this at the moment. Concretely, we rely on 1) the ascii armor delimiters, and b) availability of ascii armor headers. This also invites just dumping the data into `gpg --import`, which I guess is meant as a feature?- but might also cause problems. If we want to do this without openpgp specifics, this opens two questions: 1) how to delimit, and b) where to put metadata?

If it makes our format complex, I'm not so sure the compatibility is worth it. Some brainstorming on how a message could look if we drop html and openpgp handleability:

```
Autocrypt-Timestamp: 123456789
Autocrypt-Prefer-Encrypt: nopreference
-
<base64 of key>
-
<base64 of historical key>
```

Delimiting lines could be empty or some other delimiter as well. This would work for any future autocrypt key format, doesn't require timestamps to be parts of keys, is straightforward to implement, is hard to misuse, but is still fairly handleable for someone who knows how to base64 -d before a gpg --import.

I'll leave it at this, it's already a wall of text. Thoughts? Is this a direction we want to explore, or do we want to keep relying on the openpgp format?

**Comment by dkg** [comment]
This is a tough problem, and i think it'd be great to have a higher-bandwidth conversation about our options.  I don't know how many delimiting formats we want to ask implementers to support. the proposal above looks like yet another type of delimiter (`-`), which makes me a little sad.

I do sympathize with trying to make sure Autocrypt isn't formally tied to OpenPGP for the future, though.

**Comment by r10s** [comment]
> We should probably at some point introduce a notion of historical keys into the spec. I wonder if that point is now, though 

Totally agree.

And it seems to be even more complicated to decide what to do with the multiple/historical keys than to find a way to transport them.

So, maybe we can leave the format for level 1.0 just "as is".  At a later time we could switch to Vincent's proposal (or back to the inner MIME or to whatever). Older Autocrypt implementation would just skip the Delimiters/MIME stuff then (because they only read inside the -----BEGIN / -----END fences).
 
This would not add an extra format to the current level, making things easier for the implementers today.

**Comment by dkg** [comment]
I think #275 resolves this cleanly because it means we have a chance to stuff extra material after the first ASCII-armored OpenPGP block, and simple clients will ignore it.

**Comment by hpk42** [comment]
I think #275 does not resolve this issue.  But i am ok to remove the "level 1 functionality freeze" label from this issue here (and will do so after sending this comment in).

**Comment by hpk42** [comment]
Looking at this from 2024, i don't think anymore there is a practical use for multiple OpenPGP keys in an autocrypt setup messages.   I've not heart about this being a practical problem. It is not for Delta chat, one of the Autocrypt implementations.
