### ISSUE TITLE
Sign/Encrypt recommendation

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#3]
It's gotta come up at some point :)

I'd like to put a recommendation into the spec about how to handle signing and encryption. I think that quite simply, that recommendation should be that there are only two cryptographic e-mail modes exposed to the user: "Unencrypted", meaning plain text, or "secure", meaning signed+encrypted. (modulo wording)

I believe that having either signed-only or encrypted-only mode requires at least basic knowledge about asymmetric crypto from the user, otherwise they will take uninformed security-relevant decisions. Knowledge about asymmetric crypto should quite clearly be not a requirement to use an autocrypt-enabled client.

**Comment by dkg** [comment]
For simplicity's sake, i think i agree with @Valodim here, as long as he's talking about what an Autocrypt level 0 MUA SHOULD generate without user intervention.  I *don't* think that an Autocrypt level 0 MUA should be prohibited from being able to send signed-only messages if it wants to expose some non-Autocrypt UI/UX (e.g. messages to a public mailing list).

However, the MUAs still need to be able to handle incoming messages that might be in different forms, including signed-only or encrypted-only mails.  Again, depending on the UI exposed to the user, we should help the MUA implementers think about how they want to deal with these incoming messages in the most helpful way possible.

**Comment by Valodim** [comment]
Sort of related: Every once in a while we get an issue like [this](https://github.com/k9mail/k-9/issues/1888). We need to constantly remind ourselves that users *do not* understand what is going on with asymmetric crypto.

I suggest the following recommendations:
- have "send securely", meaning sign+encrypt, as encouraged workflow
- keep "sign cryptographically" around as supported workflow. What this means for me is that I will hide this, both on the sending and receiving sides, unless 
- make "encrypt only" an explicitly not supported workflow. Personally, I'm of the opinion that encrypt only is a very bad idea in general, but people keep arguing they want it. In this scenario however, where we attach our public key in the headers, there really can be no argument for encrypt-only.

**Comment by brunnre8** [comment]
Please keep *sign only* around.

This is especially needed if one uses mailing lists. The content is public and I can't address it to all the possible keys in the world... But still want to verify it was me who sent the content.


I get that it should be easy by default, but please don't overshoot and remove functionality that is in use **and meaningful**

**Comment by Valodim** [comment]
Noone has been disagreeing on that.

**Comment by dkg** [comment]
On Sat 2016-12-31 06:38:58 -0500, Vincent Breitmoser wrote:
> Sort of related: Every once in a while we get an issue like [this](https://github.com/k9mail/k-9/issues/1888). We need to constantly remind ourselves that users *do not* understand what is going on with asymmetric crypto.
>
> I suggest the following recommendations:
> - have "send securely", meaning sign+encrypt, as encouraged workflow
> - keep "sign cryptographically" around as supported workflow. What
> this means for me is that I will hide this, both on the sending and
> receiving sides, unless

"unless" what?

> - make "encrypt only" an explicitly not supported
> workflow. Personally, I'm of the opinion that encrypt only is a very
> bad idea in general, but people keep arguing they want it. In this
> scenario however, where we attach our public key in the headers, there
> really can be no argument for encrypt-only.

The main argument i've heard is that people want "deniability", but i'm
also not convinced that this is meaningful in any particularly useful
context.

        --dkg

**Comment by Valodim** [comment]
"unless explicitly enabled". I had edited the message right after submitting, to focus less on what I do :)

**Comment by npdoty** [comment]
Does anything need to be specified for how Autocrypt handles signed incoming messages? I see in the spec the capability for picking up the public key of a correspondent based on a cryptographically-signed email (even from a non-Autocrypt client, yeah?), which I think is awesome. But otherwise, Autocrypt users will receive encrypted and unencrypted emails from Autocrypt clients, encrypted and unencrypted emails from non-Autocrypt clients -- they should simply decrypt where possible and pick up keys from signatures and Autocrypt headers.

There might be a UI recommendation not to give the user a Secure/Green Lock UI if an email is encrypted but unsigned (or signed but not encrypted), but I'm not sure that's necessary for interoperability. Some users might care and have more detailed email clients that distinguish between encrypted and signed and just encrypted, even if most shouldn't bother with that.

**Comment by azul** [comment]
I think the main part of this was fixed in #92 as a sideeffect by specifying that by encrypt we mean sign+encrypt.
@npdoty, importing keys for signatures should be part of #72.
Not sure what we should do ui wise though. I don't think we will recommend anything there because clients already have practices of handling these and i don't think we can standardize them.

Closing this issue for now. Feel free to create a new issue if you'd like to see autocryp specify more behaviour wrt to signatures.
