### ISSUE TITLE
Who is autocrypt?

### ISSUE THREAD

**Issue by juga0** [autocrypt/autocrypt#355]

**Comment by hpk42** [comment]
I don't understand the question.  I guess you are not asking for yourself because you have been at meetings and know people involved her, right? Do you mean that it's not obvious for others who exactly is involved?  
please re-open this or a new issue providing more information.

**Comment by comradekingu** [comment]
@hpk42 There is the "What is Autocrypt", but no mention of anyone except "the Autocrypt team" on the landing page. It needn't be so faceless when there are so many nice people involved. In the very least, and in the interest of catering to what may be a concern for publicity, it could say something about beliefs, intent, or something otherwise humane, so that it doesn't appear so sterile.
