### ISSUE TITLE
Mailman Support for Autocrypt L1 / mailing lists 

### ISSUE THREAD

**Issue by hpk42** [autocrypt/autocrypt#357]
I started discussions with mailman developers on autocrypt integration through a mailman plugin and  [muacrypt](https://muacrypt.readthedocs.io)  -- the latter being the project where i am currently implementing various things in addition to basic L1 autocrypt support.  Barry (who maintained mailman for a decade or so) got back on my mail here:  https://www.mail-archive.com/mailman-developers%40python.org/msg16992.html  to which i answered with a rough technical sketch on how the muacrypt/mailman integration could practically work.  I repeat the core autocrypt relevant part here: 

With the current Autocrypt specification, a mailman list will need to have the DMARC-mitigation "replace-from" action enabled to a) allow the list's public key to be added to outgoing mails in an Autocrypt compliant way b) send properly signed and encrypted mail  to those subscribers which are Autocrypt-capable and have a "mutual"  prefer-encrypt settings.

**Comment by Valodim** [comment]
Related issue #226. Let's scope this issue to *encrypting* mailing lists.

I have a very general thought about e2e with mailing lists, that we should get a clear picture on before we proceed: What exactly does (or should) it mean to receive an encrypted e-mail from a mailing list?

The answer opens up a spectrum:
- At the minimum, it means the remailer encrypted to us, but nothing else. Specifically, the message may have been received by the remailer in plaintext, sent to other participants in plaintext, or even published in a public archive.
- At most, it means the message is not published and has never been transferred in plaintext to any participant.

And of course, anywhere inbetween.

I would really like us to have a firm understanding of what an encrypted mail from an Autocrypt-compliant remailer means here. Otherwise we will end up with very inconsistent UX for this use case, which I fear could be very hurtful to the Autocrypt ecosystem as a whole.

**Comment by dkg** [comment]
In this comment, i'm staying within the scope of @Valodim's suggestion: "encrypting mailing lists" (if you want to talk about using Autocrypt to protect the control channel of a mailing list, or just using Autocrypt for end-user authentication, etc, let's discuss that on a separate issue).

it seems clear to me that the design @hpk42 is proposing for the opportunistic mailman support is *not* "e2e" in any strict sense of the word.  The "ends" of a mailing list are the people using it, and message traversing a decrypt/reencrypt re-mailer is not end-to-end encrypted.

So i would avoid saying "e2e" in this context if we don't mean it.  That doesn't mean that "encrypted mailing lists" aren't useful, but it does mean that the semantics can get blurry, and it's possible that the semantic inconsistencies are damaging to our attempt to tell a simple and coherent story in other contexts where Autocrypt is useful.

In some sense, the simplest and clearest semantics would involve a "strict Autocrypt encrypted mailing list" that would have something like the following configuration:
 * not publicly archive messages
 * not accept subscriptions without having an autocrypt-delivered key
 * have a way for participants to know to whom messages will be re-mailed (there's a race condition here, even if we trust the remailer to not lie to us, but the race condition is probably not the end of the world).  note that this is *not* the expected default on other mailing lists, though.
 * kick people from the list if their autocrypt key disappears or fails  (if a user is kicked, who gets notified?)
 * announce the list's key as `prefer-encrypt=mutual` (?)
 * bounce messages that were sent to it in the clear?  (this seems like an argument for having a `prefer-encrypt=mandatory` but boy that is not L1 so yikes).  or, if the message is sent to it in the clear, then just re-send it in the clear, and do not try to encrypt.  how does that interact if it knows about a "prefer-encrypt=mutual" setting for Alice, but not for Bob?

I note that a discussion guided by these "strict" properties seems pretty similar to a group e-mail where everyone is in Cc:, with the exception of the remailer in the mix :/ -- what advantage does this give over group e-mail?

Still, this proposed "strict" variant is fuzzier than i'd like; and an attempt to imagine a less-strict "autocrypt-enabled" mailing list definitely makes things fuzzier.  what if some members don't even have functional autocrypt keys?  can i send it an encrypted mail that it will resend (to anyone) in the clear?  can i send the list a cleartext mail that it will encrypt to some users?  Will it re-send the encrypted message only to those users that have an autocrypt key, but not all?  what does it mean for me as a user to click "encrypt" when i mail the list?  (this is the inverse of @Valodim's question "what does it mean to receive an encrypted e-mail from a mailing list?")

finally, if Alice sends an encrypted message to the mailing list that both she and Bob are on, and Bob feels the need to follow up off-list, and has never exchanged e-mails directly with Alice, is there a way for the mailing list to facilitate that first direct Bob→Alice contact without leaking it in the clear?

This is a complicated set of questions, but i don't feel particularly close to answering them, and i would be super bummed if trying to answer them with an implementation meant that an Autocrypt user felt confused and uncertain about clicking "encrypt" when sending mail in general.

@hpk42 maybe it would make more sense to start from a user story or two to try to tease apart the utility of this proposal?  understanding how to implement it seems like it might be the easy part compared with figuring out how to present it simply and sanely to the user.

**Comment by dkg** [comment]
One other question worth pondering -- when a message arrives from an encrypted mailing list, who is the message signed by?  how does the user verify the signature?

**Comment by dkg** [comment]
And, I just wanted to add one other possible approach to these proposals, besides the "strict" and "less-strict" sketches i've made above: the proxy-encryption scheme, which i first saw implemented in [PSELS](http://www.ncsa.illinois.edu/People/hkhurana/ICICS.pdf) (PSELS uses El Gamal, but presumably we'd use Curve25519 today -- i don't think there's a way to do this scheme with RSA directly).  This approach is closer to "strict", because it presumes that each member of the list must already have a key, and it adds to the strictness because the mailing list software itself never gets to see the cleartext.

To make it work smoothly, we'd likely need to define an additional OpenPGP packet, or (alternately) a new e-mail header that would transmit the proxy key.  None of this is super complex, but it's definitely not "Autocrypt L1" either, and it would *not* simply interoperate with existing e-mail clients without a bit of adjustment.

i think this gives us the closest story to "small group of people who all know each other need to have private discussion" without requiring them all to manage their Cc lists individually.  but is that enough of a win to warrant the work?  or is there some other targeted use case?

**Comment by hpk42** [comment]
Sorry, I think i wasn't clear enough what my goal with mailman/autocrypt L1 integration is (but i do mention it in the linked mm-dev post): _opportunistically_ encrypted mailing lists.  A modest use case with that is to protect subscribers from their particular providers reading/intercepting the messages (but opportunistically, not in a guaranteed or strict way). If the remailer and a subscriber are in prefer-encrypt=mutual mode  encryption between them can easily happen.  In this way the subscriber is protected from her provider who cannot read the mail unless another subscriber uses the same provider in cleartext -- but hey, it's opportunistic.  

Note that my mm-dev suggestion says that the mailman list acts in "replace-from" mode: the mailing list will not pass through the original From, only the realname of the poster.  The message will be signed by the mailing list address's key which is always in the Autocrypt header of mail that the remailer sends. 

The whole idea also aims at incrementally getting things working out in the  wild, which then makes turning a list into "only Autocrypt subscribers are allowed" much more feasible than going for "strict mode"  directly (IMO). Strict mode will be difficult to go for before a number of public L1 compliant releases are out and in use.  

That being said, i find considerations regarding "strict" remailers or proxy-encryption interesting, it's just not in scope with the initial pragmatic approach i suggested with mm-dev.

**Comment by dkg** [comment]
right, so getting more clarity about the use cases served by opportunistically-encrypted lists is probably important here, as well as thinking carefully about how that shifts the semantics of the "encrypt" button when sending (or the "encrytped" badge on viewing).

fwiw, the "replace-from" mode, while keeping the "realname" is pretty confusing -- `Daniel Kahn Gillmor <list@example.net>` is not a header that i particularly like or want to see people sending around.

**Comment by hpk42** [comment]
in replace-from mode mm3 adds a "via" so it would be "Daniel Kahn Gillmor via LIST ... <lists@example.net>" -- maybe the "VIA" should come first, though.   But agreed, it's not a great solution as in some cases people may mistake the list address for a private address.  Then again, hiding the original poster completely makes reading ML-threads harder. 

Also I consider Autocrypt to also aim at mail apps that do not even have "encrypt" tick boxes ("replace cleartext with encrypted mail" etc.).   In that case, there is less room for confusion/expectation mismatch.  Mandating that users always know and understand how secure / well encrypted a communication situation would severely limits the reach of Autocrypt IMO.

**Comment by Valodim** [comment]
I'm very worried here that we will end up with a muddled user story of what happens when they click "the autocrypt button" during compose. The technical details about mixed-mode opportunistically encrypted mailing lists have been mostly covered here and in the other thread - and the gut feeling this leaves me with right now is "this is a really bad idea".

I suggest we take some time to discuss this in a call. Until then I would ask you to be cautious wrt expectation management (e.g. MOSS)

**Comment by hpk42** [comment]
After more IRC and one a/v discussions, i submitted [moss-muacrypt-mailman.pdf proposal](https://github.com/autocrypt/autocrypt/files/1694717/moss-muacrypt-mailman.pdf). It thus contains current thinking about the problem space which is interesting to consider, even if Mozilla does not provide a grant.

**Comment by dkg** [comment]
please see also #374 for more thoughts about encrypted mailing lists ("remailers")

**Comment by Valodim** [comment]
Closing as stale, mailing lists are not something we're actively thinking about right now. If this use case is important to anyone, feel free to reopen (also refer to #374 for our latest thoughts on the matter)
