### ISSUE TITLE
How do we deal with minor revisions?

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#378]
Didn't find anything from a quick search: How do we do minor revisions?

Point in case, what do we do with #376? It doesn't seem off enough to require a side-spec (unlike remailers), so I would put it in the main document. It does warrant a version bump though.

I remember we had a breakout session on this, was this documented somewhere?

**Comment by dkg** [comment]
i think we're talking about just bumping minor and revision numbers at the moment.  we should probably move to 1.0.1 now, since there have been enough changes in level1.rst (Terminology section, clarifications about the `Autocrypt-Gossip` header, minimizing user IDs of imported keys) to warrant a version bump.  I'm going to try to make a 1.0.1 release with the current changes and will document what was needed here.

**Comment by dkg** [comment]
should we add a revision history to the document itself, to show what changed between specific versions?

**Comment by dkg** [comment]
I've just pushed the 1.0.0-cleanup branch, which should create a proposed version 1.0.1.

@Valodim, if you could take a look at it that would be great.

It doesn't include #376, but it establishes a pattern for how to deal with changes to doc/level1.rst

if we can merge this to master and tag autocrypt-1.0.1 then we can use that as guidance for dealing with #376.

**Comment by dkg** [comment]
see #385
