### ISSUE TITLE
Autocrypt specific Multipart Content-Type for utilizing DKIM for key authenticity

### ISSUE THREAD

**Issue by jatoko** [autocrypt/autocrypt#387]
### Motivation:
Establish some trust in the authenticity of received keys through the usage of already existing and maintained trusted relationships of service providers.

### Basic Concept:
Insert some representation of the autocrypt header into the mail's body to be signed by default DKIM. To keep the principal of hiding anything that is related to keys from users, this is only done for communication partners a MUA knows to be using Autocrypt (e.g. received a key already). Receiver's MUAs may verify DKIM signature and indicate that some sort of (e.g. "level 1") sender/key-origin authenticity is given (or similar to Enigmail's "I did a quick check" option).

### Reasoning:
To my understanding, Autocrypt is designed to be independent of service providers as much as possible and greatly overcomes key propagation issues. Yet, to establish some sort of key authenticity, it cannot go beyond TOFU without workflows that are known to have usability issues for ordinary users. Or make Autocrypt dependent on service providers who sign the autocrypt header. However, most people will probably not change their e-mail, as it is well established or work related and cannot influence their providers to sign specific headers.
Though DKIM signature verification may fail for some mail setups it could contribute towards secure transparent encryption.

Please Note: I appreciate any feedback and in case this is the wrong place for this topic I will remove it.

**Comment by azul** [comment]
@jatoko I believe this is exactly the right place. Interesting approach! Never thought about it.

One issue why we have avoided adding mime parts is that they show up as attachments in many email clients and might confuse the user... (what's this thing that is attached to all your mails that i cannot open).

But maybe there are more elegant options that will still get us dkim signatures while not appearing as attachments.

**Comment by jatoko** [comment]
> what's this thing that is attached to all your mails that i cannot open

I agree and think this is also a major weakness of [pep's](https://www.pep.security/) current approach.

Using the content-type optionally and only with Autocrypt enabled correspondences should overcome this issue. As keys are exchanged via e-mails only, responding to a received Autocrypt enabled e-mail implicates an Autocrypt aware MUA on the receiver side that sould be able to deal with that content-type.
Recipients without Autocrypt ability are excluded from receiving secured emails and therefore the content-type is not included.
Users who already use/used Autocrypt on some MUAs will see their encrypted emails as attachements on some incompatible clients anyway.

Initial e-mails may still convey the pure header only.

**Comment by dkg** [comment]
thanks for bringing this suggestion here, @jatoko ! 

I agree with @azul that we probably want to avoid attachments in general.  your proposal to only send this after establishing autocrypt contact is an interesting one, but it has two potential flaws:

 * the message that we are most interested in key authenticity in is the first message!
 * not everyone is running "pure" autocrypt.  In particular, we expect that for some time to come, people will access their mail with multiple MUAs, some of which are autocrypt-capable, and others of which are not.  and each person's peer may not know of the existence of the non-autocrypt-capable MUA (e.g. if the person never sends the peer mail from it).

Looking at [DKIM's message canonicalization options](https://tools.ietf.org/html/rfc6376#section-3.4), i see several opportunities going forward if we want to pursue something like this:

 1. the sending MTA can elect to DKIM-sign the outbound Autocrypt header itself.  This is [what Posteo is doing](https://posteo.de/en/blog/new-easy-email-encryption-with-autocrypt-and-openpgp-header), and requires no changes to any existing standard.  This is the simplest, but it does require some configuration by the MTA -- in particular, they have to elect to include the Autocrypt header in the list of headers that they sign.

 2. if we're talking about accepting limitations like only in non-first messages to recipients believed to have autocrypt-capable clients, we could just mention that the `Autocrypt:` header belongs in any protected header field of an encrypted message (i.e., where the `Autocrypt-Gossip:` header goes, always remember to insert your own `Autocrypt:` header as well).  In that case, any DKIM signature that signs the body of the message will effectively include the Autocrypt header.  (this doesn't work for clearsigned messages, of course).

 3. for cleartext messages, we could encourage any Autocrypt-capable MUA to ensure that the message is some form of MIME `multipart/` (most messages today are multipart already, but even the simplest possible message (`text/plain`) can be trivially converted to `multipart/mixed` with a single child part).  If the message body is multipart, that enables the MUA to stash headers in the subparts -- so we could encourage sending MUAs to (a) copy the `Autocrypt:` header into the headers of the first subpart, and (b) encourage receiving MUAs to consider the `Autocrypt:` header from that subpart as well.

However, let's look a bit more closely at how we can expect clients to use this information i think more questions are raised by this proposal than immediately answered :) -- maybe we can answer a few of these easily:

 * For case 1, they get confirmation that the Autocrypt header was signed by the sender's MTA.  There will of course be situations where this signature doesn't appear, fails to validate, or is otherwise botched -- how should the MUA treat these two cases distinctly?

 * For case 2, the signature from the sender's MTA only signs a blinded form of the Autocrypt header -- i.e., one that they don't know what it is.  Is that a meaningful statement?  should it be given the same weight as a signature over a non-blinded header?  If the answer is that it is somehow different from a non-blinded DKIM header signature, how should the MUA behave differently?  Should this difference be extended to signatures over an Autocrypt header that happens to be "snuck" into the body and somehow "accidentally" signed by the DKIM signer?

 * for case 3, we now have two copies of an Autocrypt header -- one of them internal to the first MIME part, and one in the message headers.  if they match, no problem.  But what if they differ?  What should the receiving MUA do in that case?  Does the decision hinge on the presence of a validatable DKIM signature? if so, why?

**Comment by Valodim** [comment]
dkg gave a good overview of the situation, and I agree it would be very helpful if we could make use of  DKIM without explicit provider support.

Quickly echoing thoughts:

> One issue why we have avoided adding mime parts is that they show up as attachments in many email clients and might confuse the user.

As stated, "weirdo attachments" is indeed a *major* drawback of any attachment-based approach. Making this acceptable for users would require extreme amounts of brand awareness, something even Outlook [failed to do](https://www.google.com/search?q=att00001.bin) before.

> Using the content-type optionally and only with Autocrypt enabled correspondences should overcome this issue

While I agree this would solve the issue, it introduces two new ones:
1) Autocrypt headers have diminishing value in any mail past the first
2) This is the showstopper: Keeping track of who is an "autocrypt correspondent" is still very difficult in a multi-client scenario. Even if a user actively uses PGP/Autocrypt, if they use another client simultaneously (accepting they can't read encrypted messages), they will still see weird attachments.

I'd also add that client-side DKIM checks aren't feasible in practice. No email client does it as far as I know, and since a proper check involves DNSSEC it adds a large amount of complexity for difficult to handle error scenarios. That said, server-side DKIM checks will cause suspicious mails to be rejected or at least caught in the junk filter where they are much less likely to ever be opened.

It's an interesting thought though, and I'd like to bring another proposal to the table:

In the first message part, the sender could include an `Autocrypt-Checksum` header, which has a value of hash(keymaterial). That hash will be included in DKIM checks, and can be checked by recipients. If it doesn't match, ignore the Autocrypt header.

Pros:
+ DKIM-authenticated Autocrypt key material
+ Clear error scenario: if the checksum doesn't check out, ignore the header
+ Seamless downgrade: If either the sender or recipient doesn't support this - no biggie
+ Constant increase in message size
+ Zero user interaction - complexity is purely in the backend, and users implicitly benefit

Thoughts:
- Authenticating anything other than the key material itself would involve difficult canonicalization procedures. No way that is happening. Then again, the key material is by far the most important part.

Cons:
- Complexity :(
- Still an increase in message size
- Some implementations don't have the body part and header easily available at the same time
- Redundant if provider DKIM-signs (still worth it I'd say until GMail does it)

While this a simple idea, it's not *the simplest*: We could just move the Autocrypt header into the first part of the body. I wonder if that would cause problems? It obviously doesn't work if the outer part isn't `multipart/*`, but that's simple to fix with a wrapping `multipart/mixed`. My gut feeling is that clients and especially plugin-type openpgp implementations have an easier time accessing the message headers than inner parts, but it might be the other way around.

Lots of interesting stuff here. Thanks for bringing it up.

**Comment by jatoko** [comment]
Thank you for your feedback! I am not sure what kind of an answer you are expecting :) , so I try to contribute with my thoughts on your remarks.

> the message that we are most interested in key authenticity in is the first message!

This is true due to Autocrypt relying on the concept of TOFU. Best case scenario is that the header is part of a DKIM signature already (e.g. Posteo) but worse case scenario is that we can establish trust in the key based on TOFU + some trust chain with the second mail for the initial sender and third mail for the initial receiver - not too bad for some authentic longlasting correspondence imo.

> not everyone is running "pure" autocrypt [...]

I think I did not respect this particular issue sufficiently. Thank you!

> For case 1 [...] how should the MUA treat these two cases distinctly?
> should it be given the same weight as a signature over a non-blinded header?
> for case 3 [...] But what if they differ? What should the receiving MUA do in that case?

In regards to your remarks I suggest to follow one core principal:  Autocrypt should be operable independently of service providers.
Any behavior that cannot be influenced, enforced or guaranteed by a user (its MUA respectively) contributes to maintain the status quo. The consequence is to ignore the case where the Autocrypt header gets included in the DKIM-sig by the provider. MTA's are supposed to sign a message independently of it being blinded or clear or whatever the body includes. Only the receiver is supposed to extract the meaning of it.
Your remarks about inconsistencies: DKIM validation would "just" add another layer to the current specification; Once the key-validation succeeded, the peer-state is updated and kept until key changes force its update; all other cases result in "soft failure", and MUAs rely on the current specification.

> the sender could include an Autocrypt-Checksum header

I think this is a good representation and could lead to the right direction together with dkg's remarks.
Yet, I like to add another question: Does Autocrypt want to rely on DKIM only? Or could MUAs in the future may advertise specific authentication processes they support, e.g. keyservers such as mailvelope who offer some sort of authentic key verification (and only store keys temporal)? So the question comes down to: does Autocrypt may need a more general framework?
In such a case further headers and or parameters may be needed.

**Comment by azul** [comment]
Lot's of interesting things in here. So far my take away is that we could use DKIM signatures on the body to effectively check the autocrypt header. The main remaining questions for me are about whether this is worth the effort.

The main thing i would like to leverage dkim signatures for is to prevent spam or attackers from altering the recipients autocrypt state by faking the sender address. (I don't know if this is feasible at all... but that's something that would make it worth the effort from my point of view.)

@Valodim, you propose to ignore the header. What would the result of an ignored header be? From my point of view that would mean falling back to cleartext. (Last mail did not have any ac header as the only one that was in there was ignored). I'm not sure if that is desired.

Instead i am currently thinking about flagging autocrypt state as dkim signed once it has been observed in a mail where everything checked out. Mails that do not have valid dkim signature + AC confirmation would then not alter that state. This would imply that attackers need to be able to get valid dkim signatures on their mails to change the ac state. However... it would also mean that a user that switches from a client supporting this feature to one that does not support it would not be able to change their key anymore. Same thing if providers stop dkim signing mails.

**Comment by Valodim** [comment]
> @Valodim, you propose to ignore the header. What would the result of an ignored header be? From my point of view that would mean falling back to cleartext. (Last mail did not have any ac header as the only one that was in there was ignored).

I believe that's incorrect in the general case. If this is the first Autocrypt header then yes, it will be ignored and encryption won't be available - that seems reasonable to me. If there was an Autocrypt header before, it will only downgrade to "discouraged" after 35 days, and even then it's still available, and *even then* it's only a downgrade attack which is trivially possible by stripping Autocrypt headers.

**Comment by jatoko** [comment]
@azul 
> prevent spam or attackers from altering the recipients autocrypt state by faking the sender address. (I don't know if this is feasible at all...

I think the current specification would allow such an altering easily and I know some providers who allow arbitrary From-fields. I agree with you that this is worth the effort :)

> However... it would also mean that a user that switches from a client supporting this feature to one that does not support it would not be able to change their key anymore. Same thing if providers stop dkim signing mails.

1. I think people switching their MUAs will occur seldom or almost never; usually users only change MUAs if they also change their environment (e.g. get a new device) and even then they might even just reinstall the application that they have been using before.
2. I assume very similar real case scenario for providers to suddenly omitting dkim signatures. Maybe MUAs could advertise key changes in an authentic manner based on preceding keys or something? The latter would also be interesting for other key verification scenarios.
3. As MUA changes, private key losses and other worse case scenarios will happen, one might also applies the time frame for dkim-verified peer-states?

**Comment by dkg** [comment]
About moving the autocrypt header to the first body part: it would mean that autocrypt headers in mailing lists that add footers are likely to break/disappear, because the typical footer-adding technique is to wrap the original message body itself with a MIME multipart wrapper.  (such a re-wrapper would be breaking any dkim signature over the body too, of course)  that's a little bit sad, because it would be nice to be able to write encrypted private mail to someone i met through a mailing list, but i'm not sure how widespread that use case is.  

i suspect that normal people switch their MUAs more often than @jatoko suggests above.

I also wonder what we're expecting to be the ux difference for a user dealing with a peer with an autocrypt-discovered key vs. a user with a dkim-signed autocrypt-discovered key.  if we can't describe a useful, actionable difference, maybe we need to think more about it from that side before we dig in deeper here.

**Comment by Valodim** [comment]
see #389 for a concrete proposal and basis for discussion :)

**Comment by Valodim** [comment]
We explored this in #389 a bit, and my personal conclusion is that it's not worth the complexity. I'll shelve this for now. If anyone is interested in bringing it up again, please re-open.
