### ISSUE TITLE
Discussion: Re-use session keys for "reply to all" falllback

### ISSUE THREAD

**Issue by Valodim** [autocrypt/autocrypt#401]
An interesting idea just came up while takling with @kaie:

#### Context

When replying with an encrypted message to group of recipients, our usual approach uses [Autocrypt-Gossip](https://autocrypt.org/level1.html#key-gossip) headers to make sure the public keys of all recipients are available. This does bloat messages a bit though, and when sending many messages to many recipients the extra size piles up a bit. This issue is helped a lot with the move to ECC, but we went through some ideas to reduce the need for gossip headers in every single message.

#### Re-using session keys for reply to all

To encrypt a reply in cases where public keys of all recipients are not present, the simple idea is to encrypt using the same session key as before, and include the same PKESK packets that were included in the original message (in a sense this is the reverse of forward secrecy). So essentially, the security of the message is tied to the previous message.

This has a bunch of implications I can think of:
:+1: allows encryption without all public keys present
:+1: can be implemented independently, no interop necessary to benefit
:grey_question: uses session key from external source, can't guarantee rng properties
:-1: relies on openpgp implementation details
:-1: reuses session key
:-1: if a recipient is removed, they don't receive the message but they could still decrypt it

**Comment by nwalfield** [comment]
At least use hash(session key) to avoid session key reuse.  Perhaps this could be communicated in the openpgp message somehow.  Or, the MUA could just try it based on the threading structure.

**Comment by Valodim** [comment]
That would defeat the second :+1: up there: It would require recipients to be aware of this scheme. If we go to those lengths, gossip is probably the better and more independent way to go.

The major drawback of the idea here is that this provides one ingredient for horrible failure with crypto schemes that are vulnerable to session key reuse. Now in theory that's what IVs are for, but this definitely pushes it one step farther out the comfort zone.

**Comment by dkg** [comment]
I'm really concerned about reusing the session key.  that seems like a serious problem to me.

Can we quantify how many bytes we're talking about saving here?

If the goal is specifically byte-saving, maybe there's some other ways we can come up with to shave down the sizes of the messages, without taking the sorts of cryptographic risks this implies.

**Comment by hpk42** [comment]
In Delta Chat we avoid resending gossip-headers roughly like this:

- if the gossip-header we'd send for the recipients did change compared to the last time we send them we send the full list of gossip
- if the gossip-headers have been send last more than two days ago we send the full gossip headers
- if both conditions are not met, we do not send gossip-headers 

Now this is a bit specific to Delta Chat but it saves quite a bit of traffic/message-size and so far we have no seen complaints.  In any case this heuristic of avoiding sending gossip headersis already possible within the spec and seems to work well (others may use different heuristics).   

But for larger lists of recipients (easy to happen in chat groups) the problem rather seem to be that the pgp-packets for encrypting the session key to the recipients is significant overhead. 

so from my side we could close this issue here and have other discussions ;)
