### ISSUE TITLE
Need to transmit two certs in an autocrypt header/or two headers

### ISSUE THREAD

**Issue by teythoon** [autocrypt/autocrypt#443]
There are (at least) two reasons for that:

- v5 OpenPGP certs will have only very limited interoperability with the current v4 certs.  The way the design team pictures the transition to v5 is to have both a v5 and a v4 cert during the transition period.  Hence, we need to transmit both certs in Autocrypt.
- The user may have two certs where you don't support one of the algorithms used by the primary key.  The main use case for this is the transition to PQ algorithms.

**Comment by teythoon** [comment]
Can you please shed some light on how this issue has been fixed, or failing that re-open the issue?

**Comment by dkg** [comment]
i don't think this has been completed in the sense that you're describing, @teythoon -- rather, @hpk42 is trying to clear the decks so that the open issues in the issue tracker are ones that are actively being worked on.

We discussed the need to be able to transition between keys at the recent OpenPGP e-mail summit.  This issue looks relevant to me, if we want a key transition to happen in a phased way.  If anyone else wants to assign themselves to it, please let me know.

I think the most straightforward way is to define an `Autocrypt-2` header field.  This might also be relevant/useful for addressing #436.

**Comment by link2xt** [comment]
Somewhat related topic where I linked this issue and [OpenPGP Key Replacement draft](https://datatracker.ietf.org/doc/draft-ietf-openpgp-replacementkey/):
https://support.delta.chat/t/true-identity-key-rotation-seems-somewhat-important-in-the-long-term/3629
