### ISSUE TITLE
Support multiple keys per recipient

### ISSUE THREAD

**Issue by mkllnk** [autocrypt/autocrypt#48]
The most success I had to send encrypted messages with non-tech-savy people was with XMPP+OTR. The workflow is really easy. If I have multiple devices, they don't share a private key. They each generate there own key and they can get verified independently. You can name them like "Bob/desktop" and "Bob/mobile". Alice would know which device is active and would encrypt for that one.

With email, we don't know the device the emails are read on. So what if we encrypt the email with all known public keys for that person? We wouldn't need to share private keys. Emails could still be read on every device (that has a published encryption key). The public keys should have an expiry so that they are not stored forever.

If I add a new device, the MUA could scan the account for contacts that sent encrypted emails to me. It could send "invisible" additional key announcement emails to these contacts. That's a bit like the calendar or confirmation emails that are sent by MUAs already.

And if a device is lost, I can revoke the key of that device. A thief could still read my emails from the past, but people would stop using that key while still supporting the keys of my other devices. That enables a graceful recovery and graceful key roll-overs.

What do you think?

**Comment by dkg** [comment]
Hi mklink!  we've definitely considered the multiple-keys-per-device case. See for example the thread starting here: https://lists.mayfirst.org/pipermail/autocrypt/2017-February/000035.html

We've decided against it thus far because there seem to be a number of additional potential opportunities for use confusion (on both sides of an e-mail correspondence) in terms of unpredictably-unreadable e-mails.  we want normal users to be able to have a very clear understanding of why an encrypted e-mail might be unreadable in any given situation.  multiple keys and dynamic expiration times and mail archives seem very likely to create difficult-to-explain unreadable situations.

As for auto-sending mails to older contacts: we're not currently generating any additional e-mails beyond what is currently naturally sent by the user explicitly.  There are privacy concerns with automatically sending e-mails without user interaction, and we don't want people to have to accept that tradeoff to use autocrypt.  For example, imagine going through a bad breakup and never wanting to contact your ex again.  if you install an autocrypt client, and it sends "invisible" key announcement mails to your ex, you might be (justifiably) upset.

Finally, if you get a new device, and add a new key to it, the old messages that are stored in the archive (or currently in transit, or that are sent while your key announcements are themselves in transit) aren't going to be readable.  So some newly-arriving messages will be readable, but others will be unreadable, and the user won't know why.

It is a simpler story to tell the user initially "just use autocrypt on one client -- that's where you can read your encrypted messages".  and then add "and here's the steps you might take to enable reading your encrypted messages on other clients".  No need to explain keys, or key announcement messages, or expiration schedules, or anything like that.

**Comment by mkllnk** [comment]
Thanks, dkg, awesome reply. And it's great to see how much thought you put into everything. You gave two good reasons to discard two of my ideas:

> As for auto-sending mails to older contacts ... There are privacy concerns

Right. I agree. I had some kind of user interaction in mind. It would ask for confirmation and display the contacts. You could deselect your ex. But I agree that it's not the most convenient and doesn't scale with lots of contacts.

> if you get a new device, and add a new key to it, the old messages that are stored in the archive... aren't going to be readable.

True, that's another problem OTR doesn't need to address.

I agree that a secure form of private key exchange is the only easy way for multi-device usage.

I still don't want to share my private key with my phone which I don't trust. But that is because I use my current key for multiple purposes like software signing. I should probably have one key per purpose and a new not-so-important key for AutoCrypt. That's not something I have ever seen in best practices guides.

I still have one thought before closing the topic. We provide a convenient way, but we don't want to exclude the completely secure way, do we? So, if I decided to use multiple keys and I know the consequences of not reading old mail, can we cater for that as well? Instead of the `(email, key)` tuple, we could send `(email, [key1,key2])`. Co-MUAs would just need to exchange their public keys instead of the private key. I would assume that in any case, there would be a pairing procedure with every new device.

**Comment by Valodim** [comment]
> I still don't want to share my private key with my phone which I don't trust.

Following this premise, I believe there can be no logical conclusion other than "I can't read encrypted email on my phone". Working around this core issue by having a "lower value key" that can also go on mobile, will result in confusing communication peers with which key to actually use, yielding the (theoretical) security properties of the weakest link.

The best bet for encryption on mobile for people who don't want to store their private key is probably use of a security token, such as a Yubikey.

> But that is because I use my current key for multiple purposes like software signing.

It's absolutely reasonable to hold a key you use for software signing to a higher standard than one you would use for communication. But that's a very special scenario. For autocrypt, we assume keys are not used for other purposes. Mixing other use cases (or more keys) in makes it much harder to reason about properties (security and otherwise) of any of them.

> We provide a convenient way, but we don't want to exclude the completely secure way, do we?

Actually, yes we do. Keeping the spec as simple is possible, avoiding the feature creep where we can, is one of our core design principles. Of course, people can (and will) create their own custom solutions that do wacky things on top of autocrypt, but it's important for us to keep the friction this causes low not only for regular users, but also developers.

**Comment by mkllnk** [comment]
Okay, I'll summarise the discussion here to close it.

- We assume that the private key is only used for email and not other purposes.
- We don't want to support multi-key support, because
  * It is not needed for the AutoCrypt flow which shares a private key.
  * We want to avoid feature creep.
  * The question arises which keys to use for encryption which can be confusing.
  * The security would be the one of the weakest key.
  
Thank you.
